import urllib.request
import os
import sys
import json
import uuid

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from paths import TOKEN_FILE, read_auth, write_auth, AUTH_DIR
from utils import TONTON_API, TONTON_URL, USER_AGENT

# Retrieve or generate persistent web device identifier
def get_device():
    dev_id = read_auth("device_id") or os.environ.get("DEVICE_ID", "").strip()
    if not dev_id:
        dev_id = f"web-v3-{uuid.uuid4().hex}-{uuid.uuid4().hex}"
    if not read_auth("device_id"):
        write_auth("device_id", dev_id)
    return dev_id

DEVICE_ID = get_device()
EMAIL = (os.environ.get("EMAIL", "").strip() or read_auth("email")).strip()
PASSWORD = (os.environ.get("PASSWORD", "").strip() or read_auth("password")).strip()

if EMAIL:
    last_email = read_auth("last_email")
    if last_email and last_email != EMAIL:
        profile_dir = os.path.join(AUTH_DIR, "browser_profile")
        if os.path.exists(profile_dir):
            import shutil
            shutil.rmtree(profile_dir, ignore_errors=True)
        write_auth("tonton", "")
    write_auth("email", EMAIL)
    write_auth("last_email", EMAIL)

if PASSWORD and not read_auth("password"):
    write_auth("password", PASSWORD)

# Verify whether streaming token is accepted by headend
def check_token(token, device_id=None):
    if not token or len(token) < 20:
        return False
    test_url = (
        f"{TONTON_API}/api/playback.class.api.php/GOgetLiveConfig/378/1/6420323"
        f"?format=json&appID=TONTON&rate=WIFIHIGH&plt=web&manufacturer=chrome&serviceID=default"
        f"&model=Mozilla/5.0&firmwareVersion=10&appVersion=6.1.7&deviceOS=PCBROWSER&limitAdTracking=0"
        f"&pageId=live-tv&deviceId={device_id or DEVICE_ID}&loginToken={token}"
    )
    req = urllib.request.Request(test_url, headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(req, timeout=8) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            playback = data.get("playback") or data
            media = playback.get("media", {}) if isinstance(playback, dict) else {}
            streams = media.get("streams", []) if isinstance(media, dict) else []
            return bool(streams or playback.get("url") or playback.get("playbackUrl"))
    except Exception:
        return False

# Retrieve valid Tonton session token from cache or login
def get_token(force_refresh=False, allow_browser=False):
    # Strictly read token generated by refresh_token.yml when browser is disallowed
    if not allow_browser:
        cached = read_auth("tonton") or os.environ.get("TONTON_TOKEN", "").strip()
        if not cached:
            print("[Tonton Auth Error] 'auth/tonton' not found! Please run refresh_token.yml or python script/auth.py --force to generate it.")
            return ""
        return cached

    # 1. Check cached token from file if not forced
    if not force_refresh:
        cached = read_auth("tonton")
        if cached and check_token(cached, DEVICE_ID):
            return cached

    # 2. Check environment variable token if provided
    env_token = os.environ.get("TONTON_TOKEN", "").strip()
    if env_token and check_token(env_token, DEVICE_ID):
        return env_token

    print("[Tonton Auth] Logging in to watch.tonton.com.my...")
    if not EMAIL or not PASSWORD:
        print("[Tonton Auth] Missing EMAIL or PASSWORD. Login failed: Email or password maybe wrong.")
        return ""

    try:
        from playwright.sync_api import sync_playwright
        profile_dir = os.path.join(AUTH_DIR, "browser_profile")
        os.makedirs(profile_dir, exist_ok=True)
        with sync_playwright() as p:
            context = p.chromium.launch_persistent_context(
                user_data_dir=profile_dir,
                headless=True,
                args=[
                    "--disable-blink-features=AutomationControlled",
                    "--no-sandbox",
                    "--disable-dev-shm-usage",
                    "--disable-gpu",
                    "--window-size=1920,1080",
                    f"--user-agent={USER_AGENT}",
                ],
                user_agent=USER_AGENT,
                viewport={"width": 1920, "height": 1080},
                locale="en-US",
                timezone_id="Asia/Kuala_Lumpur",
                extra_http_headers={
                    "Accept-Language": "en-US,en;q=0.9,ms;q=0.8",
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
                }
            )
            context.add_init_script("""
                Object.defineProperty(navigator, 'webdriver', {get: () => undefined});
                Object.defineProperty(navigator, 'platform', {get: () => 'Win32'});
                Object.defineProperty(navigator, 'vendor', {get: () => 'Google Inc.'});
                Object.defineProperty(navigator, 'languages', {get: () => ['en-US', 'en', 'ms']});
                Object.defineProperty(navigator, 'plugins', {get: () => [1, 2, 3, 4, 5]});
                window.chrome = {runtime: {}};
            """)

            page = context.pages[0] if context.pages else context.new_page()
            popup_page = None

            def on_page(new_pg):
                nonlocal popup_page
                popup_page = new_pg

            context.on("page", on_page)

            print(f"[Tonton Auth] Loading {TONTON_URL}...")
            try:
                page.goto(f"{TONTON_URL}/", wait_until="domcontentloaded", timeout=30000)
            except Exception:
                pass

            # Wait for client router to resolve to /home or /login
            for _ in range(8):
                if "/home" in page.url or "/login" in page.url:
                    break
                page.wait_for_timeout(1000)

            # Check if already logged in via persistent session cookies
            existing_token = page.evaluate("""() => {
                try {
                    const sd = JSON.parse(localStorage.getItem('SHARED_DEVICE') || '{}');
                    const rootToken = localStorage.getItem('loginToken');
                    return (rootToken && rootToken.length > 50) ? rootToken : (sd.loginToken || sd.token || null);
                } catch(e) { return null; }
            }""")

            if existing_token and check_token(existing_token, DEVICE_ID):
                if "/home" not in page.url:
                    try:
                        page.goto(f"{TONTON_URL}/home", wait_until="domcontentloaded", timeout=15000)
                    except Exception:
                        pass
                print(f"[Tonton Auth] Page loaded: {page.url}")
                print("[Tonton Auth] Already logged in via persistent session cookies")
                context.close()
                write_auth("tonton", existing_token)
                return existing_token

            # Unauthenticated: ensure on /login page
            if "/login" not in page.url:
                try:
                    page.goto(f"{TONTON_URL}/login", wait_until="domcontentloaded", timeout=15000)
                except Exception:
                    pass
            print(f"[Tonton Auth] Page loaded: {page.url}")

            # Click Sign In button
            sign_in_texts = ["sign in", "log in", "login", "masuk", "daftar masuk"]
            sign_in_btn = None
            for btn in page.query_selector_all("button"):
                try:
                    txt = (btn.inner_text() or "").strip().lower()
                    aria = (btn.get_attribute("aria-label") or "").lower()
                    if any(kw in txt or kw in aria for kw in sign_in_texts) and btn.is_visible():
                        sign_in_btn = btn
                        break
                except Exception:
                    pass

            popup_page = None
            if sign_in_btn:
                sign_in_btn.click()
                print("[Tonton Auth] Clicked Sign In button.")

            # Wait for popup or inline SSO form
            for _ in range(15):
                if popup_page:
                    try:
                        popup_page.wait_for_load_state("domcontentloaded", timeout=3000)
                        if "id.tonton" in popup_page.url:
                            break
                    except Exception:
                        pass
                page.wait_for_timeout(1000)

            target = popup_page if popup_page else page
            print(f"[Tonton Auth] Target page URL: {target.url}")
            try:
                target.wait_for_load_state("networkidle", timeout=15000)
            except Exception:
                pass

            # Fill email
            target.wait_for_selector("input[name='username'], input[type='email'], input[id*='email']", timeout=20000)
            email_el = target.query_selector("input[name='username'], input[type='email'], input[id*='email']")
            if email_el:
                email_el.click()
                email_el.fill(EMAIL)
                page.wait_for_timeout(500)
                print(f"[Tonton Auth] Filled email: {EMAIL}")

            # Fill password
            target.wait_for_selector("input[type='password'], input[name='password']", timeout=15000)
            pass_el = target.query_selector("input[type='password'], input[name='password']")
            if pass_el:
                pass_el.click()
                pass_el.fill(PASSWORD)
                page.wait_for_timeout(500)

            # Click submit
            submit_btn = target.query_selector("button[type='submit'], input[type='submit']")
            if not submit_btn:
                for btn in target.query_selector_all("button"):
                    txt = (btn.inner_text() or "").strip().lower()
                    if any(kw in txt for kw in ["sign in", "log in", "login", "submit", "masuk", "continue"]) and btn.is_visible():
                        submit_btn = btn
                        break

            if submit_btn:
                submit_btn.click()
                print("[Tonton Auth] Submitted login form.")
                if popup_page:
                    try:
                        popup_page.wait_for_event("close", timeout=20000)
                    except Exception:
                        pass

            # Inspect SSO target for invalid credentials error
            if popup_page and not popup_page.is_closed():
                try:
                    err_msg = popup_page.evaluate("""() => {
                        const el = document.querySelector('.error, .alert, [class*="error"], [class*="alert"], [role="alert"]');
                        return el ? el.innerText.trim() : '';
                    }""")
                    if err_msg:
                        print(f"[Tonton Auth] SSO login message: {err_msg}")
                except Exception:
                    pass

            # Wait for redirection or token in localStorage
            try:
                page.wait_for_function(
                    """() => {
                        try {
                            if (window.location.href.includes('/error/SR101')) return true;
                            const root = localStorage.getItem('loginToken');
                            if (root && root.length > 50) return true;
                            const sd = JSON.parse(localStorage.getItem('SHARED_DEVICE') || '{}');
                            return !!(sd.loginToken || sd.token);
                        } catch(e) { return false; }
                    }""",
                    timeout=25000
                )
            except Exception:
                page.wait_for_timeout(5000)

            current_url = page.url
            if "/error/SR101" in current_url:
                context.close()
                print("[Tonton Auth] Login failed: Account blocked due to multiple login attempts/devices.")
                return ""

            token = page.evaluate("""() => {
                try {
                    const root = localStorage.getItem('loginToken');
                    if (root && root.length > 50) return root;
                    const sd = JSON.parse(localStorage.getItem('SHARED_DEVICE') || '{}');
                    return sd.loginToken || sd.token || null;
                } catch(e) { return null; }
            }""")

            new_dev_id = page.evaluate("""() => {
                try {
                    const sd = JSON.parse(localStorage.getItem('SHARED_DEVICE') || '{}');
                    return sd['deviceId-v3'] || sd.deviceId || localStorage.getItem('deviceId-v3') || localStorage.getItem('deviceId');
                } catch(e) { return null; }
            }""")

            context.close()

            if token and len(token) > 20:
                write_auth("tonton", token)
                if new_dev_id:
                    write_auth("device_id", new_dev_id)
                print(f"[Tonton Auth] Login successful. Saved fresh token to {TOKEN_FILE}")
                return token
            else:
                if "/error/SR101" in current_url:
                    print("[Tonton Auth] Login failed: Account blocked due to multiple login attempts/devices.")
                else:
                    print("[Tonton Auth] Login failed: Email or password maybe wrong.")
                return ""
    except Exception as e:
        print(f"[Tonton Auth Error] {e}")
        print("[Tonton Auth] Login failed: Email or password maybe wrong.")
        return ""

# Trigger automated web login to refresh Tonton token
def refresh_token():
    return get_token(force_refresh=True, allow_browser=True)
