import urllib.request
import os
import sys
import json
import uuid

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
AUTH_DIR = os.path.join(ROOT_DIR, "auth")
TOKEN_FILE = os.path.join(AUTH_DIR, "tonton")
DESKTOP_UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"

# Read credentials or token from auth directory
def read_auth(filename):
    file_path = os.path.join(AUTH_DIR, filename)
    if os.path.exists(file_path):
        try:
            with open(file_path, "r", encoding="utf-8") as f:
                return f.read().strip()
        except Exception:
            pass
    return ""

# Return desktop user-agent string for web requests
def get_ua():
    cached = read_auth("user_agent")
    if cached and not any(x in cached.lower() for x in ["headless", "bot", "crawler", "python"]):
        return cached

    ua_file = os.path.join(AUTH_DIR, "user_agent")
    if os.path.exists(ua_file):
        try:
            os.remove(ua_file)
        except Exception:
            pass

    ua = DESKTOP_UA
    os.makedirs(AUTH_DIR, exist_ok=True)
    try:
        with open(ua_file, "w", encoding="utf-8") as f:
            f.write(ua)
    except Exception:
        pass
    return ua

# Retrieve or generate persistent web device identifier
def get_device():
    dev_id = read_auth("device_id") or os.environ.get("DEVICE_ID", "").strip()
    if not dev_id:
        dev_id = f"web-v3-{uuid.uuid4().hex}-{uuid.uuid4().hex}"
    os.makedirs(AUTH_DIR, exist_ok=True)
    dev_file = os.path.join(AUTH_DIR, "device_id")
    if not os.path.exists(dev_file) or not read_auth("device_id"):
        try:
            with open(dev_file, "w", encoding="utf-8") as f:
                f.write(dev_id)
        except Exception:
            pass
    return dev_id

# Verify whether streaming token is accepted by headend
def check_token(token, device_id=None):
    if not token or len(token) < 20:
        return False
    dev = device_id or get_device()
    ua = USER_AGENT or DESKTOP_UA
    test_url = (
        f"https://headend-api.tonton.com.my/v600/api/playback.class.api.php/GOgetLiveConfig/378/1/6420323"
        f"?format=json&appID=TONTON&rate=WIFIHIGH&plt=web&manufacturer=chrome&serviceID=default"
        f"&model=Mozilla/5.0&firmwareVersion=10&appVersion=6.1.7&deviceOS=PCBROWSER&limitAdTracking=0"
        f"&pageId=live-tv&deviceId={dev}&loginToken={token}"
    )
    req = urllib.request.Request(test_url, headers={"User-Agent": ua})
    try:
        with urllib.request.urlopen(req, timeout=8) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            playback = data.get("playback") or data
            media = playback.get("media", {}) if isinstance(playback, dict) else {}
            streams = media.get("streams", []) if isinstance(media, dict) else []
            return bool(streams or playback.get("url") or playback.get("playbackUrl"))
    except Exception:
        return False

USER_AGENT = get_ua() or DESKTOP_UA
DEVICE_ID = get_device()
EMAIL = (read_auth("email") or os.environ.get("EMAIL", "")).strip()
PASSWORD = (read_auth("password") or os.environ.get("PASSWORD", "")).strip()

if EMAIL and not read_auth("email"):
    try:
        os.makedirs(AUTH_DIR, exist_ok=True)
        with open(os.path.join(AUTH_DIR, "email"), "w", encoding="utf-8") as f:
            f.write(EMAIL)
    except Exception:
        pass

if PASSWORD and not read_auth("password"):
    try:
        os.makedirs(AUTH_DIR, exist_ok=True)
        with open(os.path.join(AUTH_DIR, "password"), "w", encoding="utf-8") as f:
            f.write(PASSWORD)
    except Exception:
        pass

# Retrieve valid Tonton session token from cache or login
def get_token(force_refresh=False, allow_browser=False):
    # Strictly read token generated by refresh_token.yml when browser is disallowed
    if not allow_browser:
        return read_auth("tonton")

    dev_id = get_device()

    # 1. Check cached token from file if not forced
    if not force_refresh:
        cached = read_auth("tonton")
        if cached and check_token(cached, dev_id):
            return cached

    # 2. Check environment variable token if provided
    env_token = os.environ.get("TONTON_TOKEN", "").strip()
    if env_token and check_token(env_token, dev_id):
        return env_token

    print("[Tonton Auth] Logging in to watch.tonton.com.my...")
    if not EMAIL or not PASSWORD:
        print("[Tonton Auth] Missing EMAIL or PASSWORD. Login failed: Email or password maybe wrong.")
        return ""

    try:
        from playwright.sync_api import sync_playwright
        with sync_playwright() as p:
            browser = p.chromium.launch(
                headless=True,
                args=[
                    "--disable-blink-features=AutomationControlled",
                    "--no-sandbox",
                    "--disable-dev-shm-usage",
                    "--disable-gpu",
                    "--window-size=1920,1080",
                    f"--user-agent={USER_AGENT}",
                ]
            )
            context = browser.new_context(
                user_agent=USER_AGENT,
                viewport={"width": 1920, "height": 1080},
                locale="en-US",
                timezone_id="Asia/Kuala_Lumpur",
                extra_http_headers={
                    "Accept-Language": "en-US,en;q=0.9,ms;q=0.8",
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
                }
            )
            context.add_init_script("""
                Object.defineProperty(navigator, 'webdriver', {get: () => undefined});
                Object.defineProperty(navigator, 'platform', {get: () => 'Win32'});
                Object.defineProperty(navigator, 'vendor', {get: () => 'Google Inc.'});
                Object.defineProperty(navigator, 'languages', {get: () => ['en-US', 'en', 'ms']});
                Object.defineProperty(navigator, 'plugins', {get: () => [1, 2, 3, 4, 5]});
                window.chrome = {runtime: {}};
            """)

            page = context.new_page()
            popup_page = None

            def on_page(new_pg):
                nonlocal popup_page
                popup_page = new_pg

            context.on("page", on_page)

            page.goto("https://watch.tonton.com.my/login", wait_until="domcontentloaded", timeout=30000)
            try:
                page.wait_for_selector("input, button, a[href*='login'], a[href*='signin']", timeout=20000)
            except Exception:
                pass
            page.wait_for_timeout(2000)

            # Dismiss ad overlay if present
            for ad_sel in [".adContainer", ".adContainerSplash", "[class*='ad-overlay']", "[class*='splash']"]:
                ad = page.query_selector(ad_sel)
                if ad and ad.is_visible():
                    try:
                        ad.click(force=True)
                        page.wait_for_timeout(1000)
                    except Exception:
                        pass

            # Click Sign In button
            sign_in_texts = ["sign in", "log in", "login", "masuk", "daftar masuk"]
            sign_in_btn = None
            for btn in page.query_selector_all("button, a"):
                try:
                    txt = (btn.inner_text() or "").strip().lower()
                    aria = (btn.get_attribute("aria-label") or "").lower()
                    if any(kw in txt or kw in aria for kw in sign_in_texts) and btn.is_visible():
                        sign_in_btn = btn
                        break
                except Exception:
                    pass

            if sign_in_btn:
                sign_in_btn.click()
                print("[Tonton Auth] Clicked Sign In button.")

            # Wait for popup or inline SSO form
            for _ in range(15):
                if popup_page:
                    break
                page.wait_for_timeout(1000)

            target = popup_page if popup_page else page
            try:
                target.wait_for_load_state("networkidle", timeout=15000)
            except Exception:
                pass

            # Fill email
            target.wait_for_selector("input[name='username'], input[type='email'], input[id*='email']", timeout=20000)
            email_el = target.query_selector("input[name='username'], input[type='email'], input[id*='email']")
            if email_el:
                email_el.click()
                email_el.fill(EMAIL)
                page.wait_for_timeout(500)
                print(f"[Tonton Auth] Filled email: {EMAIL}")

            # Fill password
            target.wait_for_selector("input[type='password'], input[name='password']", timeout=15000)
            pass_el = target.query_selector("input[type='password'], input[name='password']")
            if pass_el:
                pass_el.click()
                pass_el.fill(PASSWORD)
                page.wait_for_timeout(500)

            # Click submit
            submit_btn = target.query_selector("button[type='submit'], input[type='submit']")
            if not submit_btn:
                for btn in target.query_selector_all("button"):
                    txt = (btn.inner_text() or "").strip().lower()
                    if any(kw in txt for kw in ["sign in", "log in", "login", "submit", "masuk", "continue"]) and btn.is_visible():
                        submit_btn = btn
                        break

            if submit_btn:
                submit_btn.click()
                print("[Tonton Auth] Submitted login form.")
                if popup_page:
                    try:
                        popup_page.wait_for_event("close", timeout=20000)
                    except Exception:
                        pass

            # Inspect SSO target for invalid credentials error
            if popup_page and not popup_page.is_closed():
                try:
                    err_msg = popup_page.evaluate("""() => {
                        const el = document.querySelector('.error, .alert, [class*="error"], [class*="alert"], [role="alert"]');
                        return el ? el.innerText.trim() : '';
                    }""")
                    if err_msg:
                        print(f"[Tonton Auth] SSO login message: {err_msg}")
                except Exception:
                    pass

            # Wait for redirection or token in localStorage
            try:
                page.wait_for_function(
                    """() => {
                        try {
                            if (window.location.href.includes('/error/SR101')) return true;
                            const root = localStorage.getItem('loginToken');
                            if (root && root.length > 50) return true;
                            const sd = JSON.parse(localStorage.getItem('SHARED_DEVICE') || '{}');
                            return !!(sd.loginToken || sd.token);
                        } catch(e) { return false; }
                    }""",
                    timeout=25000
                )
            except Exception:
                page.wait_for_timeout(5000)

            current_url = page.url
            if "/error/SR101" in current_url:
                browser.close()
                print("[Tonton Auth] Login failed: Account blocked due to multiple login attempts/devices.")
                return ""

            token = page.evaluate("""() => {
                try {
                    const root = localStorage.getItem('loginToken');
                    if (root && root.length > 50) return root;
                    const sd = JSON.parse(localStorage.getItem('SHARED_DEVICE') || '{}');
                    return sd.loginToken || sd.token || null;
                } catch(e) { return null; }
            }""")

            new_dev_id = page.evaluate("""() => {
                try {
                    const sd = JSON.parse(localStorage.getItem('SHARED_DEVICE') || '{}');
                    return sd['deviceId-v3'] || sd.deviceId || localStorage.getItem('deviceId-v3') || localStorage.getItem('deviceId');
                } catch(e) { return null; }
            }""")

            browser.close()

            if token and len(token) > 20:
                os.makedirs(AUTH_DIR, exist_ok=True)
                with open(TOKEN_FILE, "w", encoding="utf-8") as f:
                    f.write(token)
                if new_dev_id:
                    with open(os.path.join(AUTH_DIR, "device_id"), "w", encoding="utf-8") as f:
                        f.write(new_dev_id)
                print(f"[Tonton Auth] Login successful. Saved fresh token to {TOKEN_FILE}")
                return token
            else:
                if "/error/SR101" in current_url:
                    print("[Tonton Auth] Login failed: Account blocked due to multiple login attempts/devices.")
                else:
                    print("[Tonton Auth] Login failed: Email or password maybe wrong.")
                return ""
    except Exception as e:
        print(f"[Tonton Auth Error] {e}")
        print("[Tonton Auth] Login failed: Email or password maybe wrong.")
        return ""

# Trigger automated web login to refresh Tonton token
def refresh_token():
    return get_token(force_refresh=True, allow_browser=True)
